### ISSUE TITLE
Feature Request: Add Control functions

### ISSUE THREAD

**Issue by rrosson** [vitorgalvao/custom-alfred-iterm-script#21]
Was googling around and found Alfred2 Terminal Control (https://github.com/wkoffel/alfred-terminal-control) works with both terminal and iTerm. But since the change to setting iTerm support to Custom in Alfred it appears that the workflow is now broken. The main feature I am looking for is the ability to launch  an iTerm Profile from alfred. From what I can tell terminal-control can read the profiles but is unable to launch them. This would be an awesome feature to add.

TIA
-Ron

**Comment by stuartcryan** [comment]
Hi @rrosson definitely noted, I only intended the original scripts to cover basic commands. I will keep this in mind if and when I can set aside some development time but will admit it is low on the priorities list (just to set expectations).

Setting this to "Help wanted" if anyone has some spare dev time to look at this that would be awesome.
Cheers,
Stuart

**Comment by seesolve** [comment]
I might be able to help, but I don't have Alfred to play with. Normally, what I would do is to have Alfred run the script, and the script to present the user with a list of profile options. On the other hand, is it possible to pass text from Alfred to the script or vice versa, so the user could request a specific profile when running the script via Alfred?

**Comment by vitorgalvao** [comment]
Hello everyone,

Stuart no longer has the time to maintain these scripts, and as such has been kind enough to transfer the repository to me. I’ve shortened the code, made it always open a command in a new iTerm tab, and removed support for older iTerm version.

You might know me as [vitor from the Alfred Forums](https://www.alfredforum.com/profile/1891-vitor/) or if you’ve ever contributed to [Homebrew Cask](https://github.com/Homebrew/homebrew-cask/).

I’m reviewing issues and pull requests right now, so apologies if you’ve received this message more than once.

If I close an issue with a problem that still occurs in the new version, please [open a new issue](https://github.com/vitorgalvao/custom-alfred-iterm-script/issues/new).

[Try the new script](https://github.com/vitorgalvao/custom-alfred-iterm-script#use).
