### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by memelet** [vitorgalvao/custom-alfred-iterm-script#25]
When I issue a command, eg ".ls" -- I get nothing. Is there some way to view logs or some such?

I am using alfred 3 and iterm 3

**Comment by maxwellray** [comment]
Is your iTerm.app stored in your Applications folder? I was in your situation until I realized I never moved the app from my Downloads directory. The script should work as-is if you move iTerm.app into `/Applications`, or you can modify the script by replacing every instance of `\":Applications:iTerm.app\"` with `\"iTerm\"`, which worked fine for me with iTerm.app in `~/Downloads`

**Comment by jel111** [comment]
I have this same problem Iterm 2 version 3.0.4. Doesn't do anything.

**Comment by geostant** [comment]
If you're using iTerm 2 make sure to rename your application to iTerm from "iTerm 2", or change the script to call "iTerm\ 2"

**Comment by stuartcryan** [comment]
@Geostant, you are correct. Actually when you download iTerm the binary (as far as I have always tested) will only be called 'iTerm'. What I have seen happen most often, is the when an old/existing iTerm binary exists in the extracted location (usually Downloads), MacOS automagically appends a 2 to the binary (making it look like 'iTerm 2') which hence stops the script from working.

See for example here:
![2016-10-04_08-26-29](https://cloud.githubusercontent.com/assets/9924832/19054752/8717ba64-8a0c-11e6-94be-f33c45c781f7.png)

Then when you extract a second time:
![2016-10-04_08-28-57](https://cloud.githubusercontent.com/assets/9924832/19054771/9e1e3454-8a0c-11e6-8600-3d3f0eb25587.png)

And if you were to keep going:
![2016-10-04_08-29-30](https://cloud.githubusercontent.com/assets/9924832/19054799/b7aff5ce-8a0c-11e6-9980-b5c7be734389.png)

So the script itself, relies on the binary simply being called 'iTerm' which is the default name of the binary, permitting it is extracted into a folder where no such binary called 'iTerm' already exists.
Cheers,
Stuart

**Comment by geostant** [comment]
@stuartcryan .......Ha ha ha :)
I was living in a lie all my life thinking that I actually have iTerm and iTerm 2 (which are different)

That clears a lot 👍

**Comment by stuartcryan** [comment]
@geostant No worries, it seems to come up really often, I might have to throw something on the front page for it.

It is an unfortunate quirk that will hopefully resolve itself as more people become aware (*fingers crossed*.

**Comment by kenberkeley** [comment]
```
$ cd /Applications
$ ln -s iTerm\ 2.app iTerm.app
```

**Comment by arrra** [comment]
@geostant Thanks! Worked!
Although I do suggest to change it in the script. Stays synced with alfred when you move to new machines or even export your configs with alfred. You might actually forget to rename the iTerm2 app:)

**Comment by vitorgalvao** [comment]
Hello everyone,

Stuart no longer has the time to maintain these scripts, and as such has been kind enough to transfer the repository to me. I’ve shortened the code, made it always open a command in a new iTerm tab, and removed support for older iTerm version.

You might know me as [vitor from the Alfred Forums](https://www.alfredforum.com/profile/1891-vitor/) or if you’ve ever contributed to [Homebrew Cask](https://github.com/Homebrew/homebrew-cask/).

I’m reviewing issues and pull requests right now, so apologies if you’ve received this message more than once.

If I close an issue with a problem that still occurs in the new version, please [open a new issue](https://github.com/vitorgalvao/custom-alfred-iterm-script/issues/new).

[Try the new script](https://github.com/vitorgalvao/custom-alfred-iterm-script#use).
