### ISSUE TITLE
Check whether current terminal window is busy

### ISSUE THREAD

**Issue by nils-tekampe** [vitorgalvao/custom-alfred-iterm-script#30]
Hi there,
I just started with the iterm integration in Alfred but I'm struggling a bit with my workflow. I usually have a splitted screen of 3 or 4 terminal windows open all the time. So, I definetly prefer to post the command into one of these. However, it would be great, if Alfred could check whether the window is busy before. Specifically, open SSH sessions are usually windows that I don't want the commands ending up in.
Is there any chance that a functionality like this being realized in future?
Nils

**Comment by vitorgalvao** [comment]
[Try the new script](https://github.com/vitorgalvao/custom-alfred-iterm-script#use).

It now always opens in a new tab.
