### ISSUE TITLE
Open in new tab

### ISSUE THREAD

**Issue by marspe** [vitorgalvao/custom-alfred-iterm-script#33]
All commands run in current session (e.g. "open terminal here" from file serach). Is it intended behaviour? In most of cases, opening in new tab makes more sens for me. So, shouldn't onlywindow=False [in this line](https://github.com/stuartcryan/custom-iterm-applescripts-for-alfred/blob/master/custom_iterm_script_iterm_2.9.applescript#L17)?

**Comment by mnabialek** [comment]
To be honest I also needed opening in new tab, because I usually has multiple SSHs into docker containers so running normal command in current tab doesn't makes much sense.

It seems that it was changed a while ago to opening in current tab in here: https://github.com/stuartcryan/custom-iterm-applescripts-for-alfred/issues/26

**Comment by nielsbom** [comment]
I made a version that opens a new window: https://github.com/nielsbom/custom-iterm-applescripts-for-alfred/tree/always-open-new-window

**Comment by KKSzymanowski** [comment]
If you want to open in new tab, not new window here's what I came up with:
```
on alfred_script(q)
	if application "iTerm2" is running or application "iTerm" is running then
		run script "
			on run {q}
				tell application \"iTerm\"
					activate
					try
						select first window
						set createTab to true
					on error
						create window with default profile
						select first window
						set createTab to false
					end try
					tell the first window
						if createTab is true then
							create tab with default profile
						end if
						tell current session to write text q
					end tell
				end tell
			end run
		" with parameters {q}
	else
		run script "
			on run {q}
				tell application \"iTerm\"
					activate
					try
						select first window
					on error
						create window with default profile
						select first window
					end try
					tell the first window
						tell current session to write text q
					end tell
				end tell
			end run
		" with parameters {q}
	end if
end alfred_script
```
@stuartcryan I can make a PR if you want.

**Comment by vitorgalvao** [comment]
[Try the new script](https://github.com/vitorgalvao/custom-alfred-iterm-script#use).

It now always opens in a new tab.
