### ISSUE TITLE
Filename rename suggestion

### ISSUE THREAD

**Issue by plutotree** [vitorgalvao/custom-alfred-iterm-script#34]
My iterm version is v3.2.0,  `custom_iterm_script_iterm_3.1.1.applescript` works fine for me.

It should rename to `custom_iterm_script_iterm_3.applescript`, it will be better. The same as the other filename.

**Comment by neontapir** [comment]
Please do. The filename was confusing to me initially. I wasn't sure if it would work for higher versions.

**Comment by vitorgalvao** [comment]
[Try the new script](https://github.com/vitorgalvao/custom-alfred-iterm-script#use).

Scripts no longer have versions in the names.
