### ISSUE TITLE
Issues with "quake window" feature in iTerm 2.9+

### ISSUE THREAD

**Issue by stuartcryan** [vitorgalvao/custom-alfred-iterm-script#6]
(From http://www.alfredforum.com/topic/7138-custom-terminal-script-integrate-iterm-with-alfred-updated-august-19-2015/#entry38822) I'm using iTerm's "quake window" feature (I have a specific half-screen sized window,that drops when I hit the `~` (tilda) button). This opens a new tab in that profile, but doesn't activate the actual window.

It may be related to this bug I previously opened for iTerm, which is sort-of related to activating the "hotkey profile".

...
...
I'm on the bleeding edge of iTerm I think (Build 2.9.20150812-nightly)

Also, this is funny, but I'm actually experiencing different results whether I'm cmd+tabbing away from that hotkey window or if I'm hiding it with the hotkey itself (I get a new tab in a new window vs. new tab in the hotkey profile window). This actually is related to the iTerm bug I posted, haha

**Comment by UA-WP-admin** [comment]
Came to post about this. I tried adding some applescript to trigger the hotkey that I have set for showing the hotkey window, but had no luck.

**Comment by skyshab** [comment]
I came to post about this issue. I tried adding some applescript to trigger the hotkey that I use for the Hotkey Window, but had no luck.

**Comment by paanvaannd** [comment]
I tried doing the same, I would like to see the hotkey trigger first to check to make sure that the "quake window" window option is not being used first and then create a new tab if it is currently not being used.

**Comment by ashkan-leo** [comment]
I'm also getting different unexpected behaviors. It actually becomes worse if I connect multiple displays to my MacBook. Sometimes nothings happens, sometimes it works fine.

**Comment by vitorgalvao** [comment]
Closing as new script is different and support for pre-v3 iTerm has been dropped.
