### ISSUE TITLE
Enable behaviour selection of opening in new/existing tabs etc

### ISSUE THREAD

**Issue by stuartcryan** [vitorgalvao/custom-alfred-iterm-script#7]
(Form http://www.alfredforum.com/topic/7138-custom-terminal-script-integrate-iterm-with-alfred-updated-august-19-2015/#entry38822 ) I would also be interesting to be able to choose whether the script ( opens a new tab / reuses one tab _it opened_ / opens a window / reuses one window it opened ). Don't know if that's feasible, but I would definitely choose a reused tab/window instead of a new one every time.

...
Me:
Also with regards to the new feature, that is possible but it would be on an all or nothing basis, i.e. it can't really be set at run time. So are you looking for a set one off to change how the script as a whole runs or are you looking for something you can change each time it runs depending on what behaviour you would like at that time (just wanting to clarify, as the latter is not really possible).

...
MD:
As for the new feature - would it be like a boolean you configure at the top of the script? Or actually a different script? I want to understand what "all or nothing" means, I don't mind if it's not configurable in a UI, but would love a way to be able to quickly change it in the custom script code.

...
Me:
I was actually thinking along the lines of a boolean in the script itself (rather than a separate script). So I think that would suit exactly what you are looking for.

**Comment by hindman** [comment]
+1 for this feature. In my case, I almost always (probably 99% of time) want to run shell commands in the current iTerm tab. I might experiment to see if I can get this working ... but my AppleScript chops are basically zero.

**Comment by vitorgalvao** [comment]
Closing as new script is different and it now always opens in a new tab.
