### ISSUE TITLE
Terminal Command in New Tab

### ISSUE THREAD

**Issue by wynnsyt** [vitorgalvao/custom-alfred-iterm-script#9]
I have several workflows that run terminal commands. I would expect the commands are run in a new tab, as in the official implementation before. 

Since the official support was deprecated, quite often the desired command runs in an existing iTerm tab, and a new tab is created in the foreground. Particularly this happens whenever I have split panes open.

This is quite annoying not only because it disrupts my work in the current tab, but it also defeats the purpose why I choose to use a terminal command instead of "run script", as I want to check on the output (download progress, for example).

I am using iTerm2 2.1.1, and my default shell is Fish, if that is at all helpful.

**Comment by stuartcryan** [comment]
Hi wynnsyt,
Just wanted to let you know that I have seen your issue, currently this weekend I am in lockdown for assignment work (assignments due Monday) so I will have a look at this within the next week.
Cheers,
Stuart

**Comment by stuartcryan** [comment]
Hi Wynnsyt,
The commands should each run in a new tab and never in an existing tab (as that is replicated from the old official behaviour).

Can you please try with the latest version and let me know if this still exists (as there have been a few changes).

If it does I might need to get you to take some screenshots of your iTerm configuration so I can try to replicate the issue.
Cheers,
Stuart

**Comment by wynnsyt** [comment]
Hi Stuart,

Thanks for your attention.

Using the latest version I am seeing this occur less frequently. However, when I have split panes open, the script still opens a blank tab and runs the command in an existing tab.

[Here](http://imgur.com/a/x7WK9#0) are my iTerm preferences.

**Comment by stuartcryan** [comment]
Thanks for the update, I will have a look through and see if I am able to replicate this further for you.
Cheers,
Stuart

**Comment by augint** [comment]
Hi Wynnsyt,
Try this:
-- This is v0.5 of the custom script for AlfredApp for iTerm 2.9+
-- Please see https://github.com/stuartcryan/custom-iterm-applescripts-for-alfred/
-- for the latest changes.

on is_running(app_name)
	tell application "System Events" to (name of processes) contains app_name
end is_running

-- Please note, if you store the iTerm binary in any other location than the Applications Folder
-- please ensure you update the two locations below (in the format of : rather than / for folder dividers)
-- this gets around issues with AppleScript not handling things well if you have two iTerm binaries on your system... which can happen :D

on alfred_script(q)
	if is_running("iTerm2") or is_running("iTerm") or is_running("iTerm 2") then
		run script "
			on run {q}
				tell application \":Applications:iTerm 2.app\"
					activate
					try
						select first window
						set onlywindow to false
					on error
						create window with default profile
						select first window
						set onlywindow to true
					end try
					tell the first window
						tell current session to write text q
					end tell
				end tell
			end run
		" with parameters {q}
	else
		run script "
			on run {q}
				tell application \":Applications:iTerm 2.app\"
					activate
					try
						select first window
					on error
						create window with default profile
						select first window
					end try
					tell the first window
						tell current session to write text q
					end tell
				end tell
			end run
		" with parameters {q}
	end if
end alfred_script

**Comment by wynnsyt** [comment]
augint: 
Thanks for your reply but sorry I cannot test with your fix because my iTerm is on 2.1.4 for the moment.

For anyone having this problem, please refer to [acook's fix](https://github.com/stuartcryan/custom-iterm-applescripts-for-alfred/issues/14#issue-105143591)

**Comment by stuartcryan** [comment]
HI @wynnsyt,
I have not used split panes behaviour before. Is there any chance you could please do a little screenshare video showing the behaviour you are attempting to use and I will have a look at seeing if I can put together a fix for these issues.
Cheers,
Stuart

**Comment by wynnsyt** [comment]
Sorry I won't be able to help reproduce the issue because I have switched to 2.9. AFAIK the fix I mentioned above was valid at the time of posting. 

Thanks.

**Comment by loeschg** [comment]
I'm having this same issue on 2.1.4. Here's a GIF:

![alfred-issue](https://cloud.githubusercontent.com/assets/766021/14791595/1c3eb986-0adc-11e6-885b-2f4da2248eff.gif)

**Comment by stuartcryan** [comment]
Hi Greg,
Is there any chance you could try and replicate the same issue in iTerm 2.9? 

As iTerm is moving towards the new branch I am less inclined to put development work into fixing an issue in the 2.1 branch of iTerm.

If this is an issue in 2.9 (which is quite stable now from my use and more people are moving towards), I could definitely have a look for you. But as my time is limited I would prefer to dedicate it to the newer 2.9 branch of iTerm.
Cheers,
Stuart

**Comment by jnials** [comment]
I am running 2.9, specifically "Build 2.9.20160510", along with the latest Alfred (3).  It opens a new tab each time for me as well.

**Comment by vitorgalvao** [comment]
Hello everyone,

Stuart no longer has the time to maintain these scripts, and as such has been kind enough to transfer the repository to me. I’ve shortened the code, made it always open a command in a new iTerm tab, and removed support for older iTerm version.

You might know me as [vitor from the Alfred Forums](https://www.alfredforum.com/profile/1891-vitor/) or if you’ve ever contributed to [Homebrew Cask](https://github.com/Homebrew/homebrew-cask/).

I’m reviewing issues and pull requests right now, so apologies if you’ve received this message more than once.

[Try the new script](https://github.com/vitorgalvao/custom-alfred-iterm-script#use).
